/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List storages */
        get: operations["listStorages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a storage by ID */
        get: operations["getStorage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/validators/coordinate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Validate latitude and longitude values */
        get: operations["validateCoordinate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/validators/postcode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Validate a UK postcode */
        get: operations["validatePostcode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List posts */
        get: operations["listPosts"];
        put?: never;
        /** Create a post */
        post: operations["createPost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get a post by ID */
        get: operations["getPost"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Storage: components["schemas"]["StorageSummary"] & {
            /**
             * @description Posts that reference this storage listing
             * @example [
             *       {
             *         "id": "pst_101",
             *         "content": "Added two new bays with upgraded motion cameras. Reserve a slot before the weekend rush!",
             *         "createdAt": "2025-03-04T15:20:00Z",
             *         "images": [
             *           "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=1600&auto=format&fit=crop"
             *         ],
             *         "user": {
             *           "id": "usr_320",
             *           "username": "bkhost",
             *           "name": "Maya Lopez"
             *         }
             *       }
             *     ]
             */
            posts: components["schemas"]["StoragePost"][];
        };
        /** @description Condensed storage listing used in collection responses */
        StorageSummary: {
            /**
             * @description Unique storage identifier
             * @example stg_123
             */
            id: string;
            /**
             * @description Marketing headline for the listing
             * @example Secure Downtown Garage Space
             */
            title: string;
            /**
             * @description Human-readable location summary
             * @example San Francisco, CA
             */
            location: string;
            /**
             * Format: float
             * @description Recurring monthly price in USD
             * @example 249.99
             */
            pricePerMonth: number;
            /**
             * Format: float
             * @description Average customer rating
             * @example 4.8
             */
            rating: number;
            /**
             * Format: int32
             * @description Total number of reviews contributing to the rating
             * @example 124
             */
            reviews: number;
            /**
             * Format: int32
             * @description Approximate usable square footage
             * @example 200
             */
            sizeSqFt: number;
            /**
             * @description Access description (e.g. hours, entry method)
             * @example 24/7 keypad access
             */
            access: string;
            /**
             * @description Whether the space maintains climate controls
             * @example true
             */
            climateControlled: boolean;
            /**
             * Format: uri
             * @description Primary marketing image URL
             * @example https://cdn.example.com/images/stg_123_cover.jpg
             */
            image: string;
            /**
             * @description Additional gallery image URLs for the listing
             * @example [
             *       "https://cdn.example.com/images/stg_123_cover.jpg",
             *       "https://cdn.example.com/images/stg_123_interior.jpg",
             *       "https://cdn.example.com/images/stg_123_entrance.jpg"
             *     ]
             */
            images: string[];
            category?: components["schemas"]["ListingCategory"];
            /**
             * @description Optional amenity tags for the listing
             * @example [
             *       "Climate control",
             *       "24/7 security"
             *     ]
             */
            tags?: string[];
            coordinate?: components["schemas"]["ListingCoordinate"];
        };
        /** @description Post promoting a storage listing */
        StoragePost: {
            /**
             * @description Unique post identifier
             * @example pst_123
             */
            id: string;
            /**
             * @description Post content text
             * @example Fresh inventory arriving next week!
             */
            content: string;
            /**
             * @description Optional image URLs associated with the post
             * @example [
             *       "https://cdn.example.com/posts/pst_123/photo-1.jpg"
             *     ]
             */
            images?: string[];
            /**
             * @description Optional video URLs embedded in the post
             * @example [
             *       "https://videos.example.com/pst_123/teaser.mp4"
             *     ]
             */
            videos?: string[];
            /**
             * Format: date-time
             * @description When the post was created
             * @example 2025-01-05T15:30:00Z
             */
            createdAt: string;
            /** @description Author of the post */
            user: {
                /** @example usr_123 */
                id: string;
                /** @example jane */
                username: string;
                /** @example Jane Doe */
                name: string;
            };
        };
        /** @description Result of validating storage coordinates */
        StorageCoordinateValidation: {
            /**
             * Format: double
             * @description Normalized latitude value
             * @example 51.5014
             */
            latitude: number;
            /**
             * Format: double
             * @description Normalized longitude value
             * @example -0.1419
             */
            longitude: number;
            /**
             * @description Indicates the provided coordinates passed validation
             * @example true
             */
            valid: boolean;
        };
        /**
         * @description Category of storage listing
         * @example garage
         * @enum {string}
         */
        ListingCategory: "all" | "garage" | "basement" | "room" | "attic" | "outdoor";
        /** @description Geographic coordinate for a storage listing */
        ListingCoordinate: {
            /**
             * Format: float
             * @example 37.7749
             */
            latitude: number;
            /**
             * Format: float
             * @example -122.4194
             */
            longitude: number;
        };
        /** @description A user-created post highlighting a storage listing */
        Post: {
            /**
             * @description Unique post identifier
             * @example pst_123
             */
            id: string;
            /**
             * @description Post content
             * @example New units available now!
             */
            content: string;
            /**
             * @description Image URLs attached to the post
             * @example [
             *       "https://cdn.example.com/posts/pst_123/photo-1.jpg",
             *       "https://cdn.example.com/posts/pst_123/photo-2.jpg"
             *     ]
             */
            images?: string[];
            /**
             * @description Video URLs embedded in the post
             * @example [
             *       "https://videos.example.com/pst_123/intro.mp4"
             *     ]
             */
            videos?: string[];
            /**
             * Format: date-time
             * @description Creation timestamp
             * @example 2025-01-01T12:00:00Z
             */
            createdAt: string;
            user: {
                /** @example usr_123 */
                id: string;
                /** @example jane */
                username: string;
                /** @example Jane Doe */
                name: string;
            };
            /**
             * @description Storage listing referenced by this post
             * @example {
             *       "id": "stg_123",
             *       "title": "Secure Downtown Garage Space",
             *       "location": "San Francisco, CA",
             *       "pricePerMonth": 249.99,
             *       "rating": 4.8,
             *       "reviews": 124,
             *       "sizeSqFt": 200,
             *       "access": "24/7 keypad access",
             *       "climateControlled": true,
             *       "image": "https://cdn.example.com/images/stg_123_cover.jpg",
             *       "images": [
             *         "https://cdn.example.com/images/stg_123_cover.jpg",
             *         "https://cdn.example.com/images/stg_123_interior.jpg"
             *       ],
             *       "category": "garage",
             *       "tags": [
             *         "Climate control"
             *       ]
             *     }
             */
            storage: components["schemas"]["StorageSummary"];
        };
        /** @description Payload to create a post for a specific storage listing */
        PostCreate: {
            /** @example New units available now! */
            content: string;
            /**
             * @description Author user id
             * @example usr_123
             */
            userId: string;
            /**
             * @description Storage id to attach to the post
             * @example stg_123
             */
            storageId: string;
            /**
             * @description Optional image URLs for the post gallery
             * @example [
             *       "https://cdn.example.com/posts/pst_123/photo-1.jpg"
             *     ]
             */
            images?: string[];
            /**
             * @description Optional video URLs for the post
             * @example [
             *       "https://videos.example.com/pst_123/intro.mp4"
             *     ]
             */
            videos?: string[];
        };
        /** @description Result of validating a UK postcode against the Postcodes.io dataset */
        PostcodeValidation: {
            /**
             * @description Normalized postcode string with uppercase letters and a single space between outward and inward parts
             * @example SW1A 1AA
             */
            postcode: string;
            /**
             * @description Indicates whether the postcode resolved to a known location
             * @example true
             */
            valid: boolean;
            /**
             * Format: double
             * @description Latitude of the postcode centroid when available
             * @example 51.501009
             */
            latitude?: number | null;
            /**
             * Format: double
             * @description Longitude of the postcode centroid when available
             * @example -0.141588
             */
            longitude?: number | null;
            /**
             * @description Top-level administrative region for the postcode
             * @example London
             */
            region?: string | null;
            /**
             * @description Country that contains the postcode
             * @example England
             */
            country?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /** Format: date-time */
                        time?: string;
                    };
                };
            };
        };
    };
    listStorages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageSummary"][];
                };
            };
        };
    };
    getStorage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Storage"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                    };
                };
            };
        };
    };
    validateCoordinate: {
        parameters: {
            query: {
                /** @description Latitude value to validate */
                latitude: string;
                /** @description Longitude value to validate */
                longitude: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Coordinates are valid */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageCoordinateValidation"];
                };
            };
            /** @description Invalid coordinates */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                    };
                };
            };
        };
    };
    validatePostcode: {
        parameters: {
            query: {
                /** @description Postcode string to validate. Whitespace is normalized and comparison is case-insensitive. */
                postcode: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Postcode validation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostcodeValidation"];
                };
            };
            /** @description Missing postcode input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                    };
                };
            };
        };
    };
    listPosts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Post"][];
                };
            };
        };
    };
    createPost: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Post"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                    };
                };
            };
        };
    };
    getPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Post"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                    };
                };
            };
        };
    };
}
