import { StyleSheet } from 'react-native';
import { palette, theme } from '@/theme';

export const homeStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.background,
  },
  container: {
    flex: 1,
    backgroundColor: palette.background,
  },
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.background,
    paddingHorizontal: 24,
    gap: 12,
  },
  loadingLabel: {
    ...theme.typography.caption,
    color: palette.textSubtle,
  },
  listContent: {
    paddingBottom: 48,
  },
  headerContainer: {
    paddingTop: 24,
    paddingBottom: 20,
    paddingHorizontal: 24,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTitleGroup: {
    flexDirection: 'column',
  },
  headerTitle: {
    ...theme.typography.hero,
    color: palette.text,
  },
  headerSubtitle: {
    ...theme.typography.caption,
    color: palette.textSubtle,
    marginTop: 4,
  },
  headerActions: {
    flexDirection: 'row',
    gap: 12,
  },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 16,
    backgroundColor: palette.surface,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0F172A',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },
  searchWrapper: {
    marginTop: 24,
    position: 'relative',
  },
  searchInput: {
    height: 52,
    borderRadius: 20,
    paddingLeft: 52,
    paddingRight: 96,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.divider,
    ...theme.typography.body,
    color: palette.text,
  },
  searchIcon: {
    position: 'absolute',
    left: 20,
    top: 16,
  },
  searchTrailingGroup: {
    position: 'absolute',
    right: 12,
    top: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  searchClearButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchFilterButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#EEF2F7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  chipsScroll: {
    marginTop: 20,
    paddingLeft: 24,
  },
  chipsContent: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingRight: 12,
    gap: 12,
  },
  chip: {
    paddingHorizontal: 18,
    paddingVertical: 8,
    borderRadius: 18,
    backgroundColor: '#E9ECF8',
  },
  chipActive: {
    backgroundColor: palette.primary,
  },
  chipLabel: {
    ...theme.typography.caption,
    color: palette.textMuted,
  },
  chipLabelActive: {
    color: '#FFFFFF',
  },
  sectionHeader: {
    marginTop: 28,
    marginBottom: 16,
    paddingHorizontal: 24,
  },
  sectionTitle: {
    ...theme.typography.subtitle,
    color: palette.text,
  },
  storyCard: {
    flexDirection: 'row',
    backgroundColor: palette.surface,
    borderRadius: 22,
    padding: 16,
    gap: 16,
    marginBottom: 16,
    marginHorizontal: 24,
    shadowColor: '#111827',
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  storyImage: {
    width: 96,
    height: 96,
    borderRadius: 18,
    backgroundColor: palette.surfaceAlt,
  },
  storyBody: {
    flex: 1,
    justifyContent: 'space-between',
  },
  storyCategoryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  storyCategoryBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 14,
    backgroundColor: palette.highlight,
  },
  storyCategoryLabel: {
    ...theme.typography.caption,
    fontWeight: '600',
    color: palette.primary,
    textTransform: 'uppercase',
  },
  storyTimestamp: {
    ...theme.typography.caption,
    color: palette.textSubtle,
  },
  storyTitle: {
    ...theme.typography.body,
    fontWeight: '600',
    color: palette.text,
    lineHeight: 22,
    marginTop: 6,
  },
  storySummary: {
    ...theme.typography.caption,
    color: palette.textMuted,
    lineHeight: 18,
    marginTop: 8,
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
    paddingHorizontal: 24,
  },
  emptyTitle: {
    ...theme.typography.subtitle,
    color: palette.text,
    marginBottom: 8,
  },
  emptySubtitle: {
    ...theme.typography.caption,
    color: palette.textSubtle,
    textAlign: 'center',
    paddingHorizontal: 24,
  },
  filterOverlay: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    position: 'relative',
  },
  filterBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
  },
  filterSheet: {
    width: '100%',
    maxWidth: 440,
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
    shadowColor: '#0F172A',
    shadowOpacity: 0.16,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 16 },
    elevation: 12,
    zIndex: 1,
  },
  filterHeader: {
    backgroundColor: '#111827',
    paddingHorizontal: 24,
    paddingVertical: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  filterHeaderTitle: {
    ...theme.typography.subtitle,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  filterCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.14)',
  },
  filterBody: {
    maxHeight: 480,
  },
  filterContent: {
    paddingHorizontal: 24,
    paddingVertical: 24,
    gap: 24,
  },
  filterResetRow: {
    alignItems: 'flex-end',
  },
  filterResetButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  filterResetText: {
    ...theme.typography.caption,
    color: palette.primary,
    fontWeight: '600',
  },
  filterField: {
    gap: 12,
  },
  filterLabel: {
    ...theme.typography.caption,
    color: palette.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  filterSelect: {
    height: 48,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.divider,
    backgroundColor: palette.surface,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  filterSelectActive: {
    borderColor: palette.primary,
    backgroundColor: '#F8FAFF',
  },
  filterSelectValue: {
    ...theme.typography.body,
    color: palette.text,
  },
  filterSelectPlaceholder: {
    color: palette.textSubtle,
  },
  filterOptionList: {
    borderWidth: 1,
    borderColor: palette.divider,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    marginTop: 4,
    paddingVertical: 4,
    overflow: 'hidden',
    shadowColor: '#0F172A',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 8,
  },
  filterOptionSearch: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    backgroundColor: '#F8FAFC',
  },
  filterOptionSearchIcon: {
    marginTop: 1,
  },
  filterOptionSearchInput: {
    flex: 1,
    ...theme.typography.caption,
    color: palette.text,
  },
  filterOptionScroll: {
    maxHeight: 200,
    paddingVertical: 4,
  },
  filterOption: {
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  filterOptionActive: {
    backgroundColor: '#EEF2FF',
  },
  filterOptionLabel: {
    ...theme.typography.body,
    color: palette.text,
  },
  filterOptionLabelActive: {
    color: palette.primary,
    fontWeight: '600',
  },
  filterOptionEmpty: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterOptionEmptyText: {
    ...theme.typography.caption,
    color: palette.textSubtle,
  },
  filterRow: {
    flexDirection: 'row',
    gap: 20,
    flexWrap: 'wrap',
  },
  filterColumn: {
    flex: 1,
    gap: 12,
    minWidth: 160,
  },
  filterFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingVertical: 20,
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
  },
  filterSecondaryButton: {
    flex: 1,
    height: 48,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  filterSecondaryLabel: {
    ...theme.typography.body,
    color: palette.text,
    fontWeight: '600',
  },
  filterPrimaryButton: {
    flex: 1,
    height: 48,
    borderRadius: 16,
    backgroundColor: '#111827',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 12,
  },
  filterPrimaryLabel: {
    ...theme.typography.body,
    color: '#FFFFFF',
    fontWeight: '600',
  },
});
