import { StyleSheet } from 'react-native';
import { palette, theme } from '@/theme';

export const homeStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.background,
  },
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingHorizontal: 24,
    backgroundColor: palette.background,
  },
  loadingLabel: {
    ...theme.typography.caption,
    color: palette.textMuted,
  },
  root: {
    flex: 1,
  },
  contentShell: {
    flex: 1,
    alignItems: 'center',
  },
  contentInner: {
    width: '100%',
    maxWidth: 420,
    flex: 1,
  },

  headerCard: {
    backgroundColor: palette.surface,
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    paddingTop: 32,
    paddingBottom: 24,
    paddingHorizontal: 24,
    shadowColor: '#1F2933',
    shadowOpacity: 0.04,
    shadowRadius: 26,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  greetingGroup: {
    flex: 1,
    gap: 2,
  },
  greeting: {
    ...theme.typography.subtitle,
    color: palette.text,
  },
  greetingSubhead: {
    ...theme.typography.caption,
    color: palette.textSubtle,
  },
  createButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 18,
    backgroundColor: palette.primary,
  },
  createButtonIcon: {
    marginBottom: -1,
  },
  createButtonLabel: {
    ...theme.typography.caption,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  encouragementCard: {
    marginBottom: 20,
    paddingHorizontal: 18,
    paddingVertical: 16,
    borderRadius: 20,
    backgroundColor: `${palette.primary}14`,
    borderWidth: 1,
    borderColor: `${palette.primary}26`,
    gap: 10,
    position: 'relative',
  },
  encouragementTitle: {
    ...theme.typography.caption,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    color: palette.primary,
  },
  encouragementCopy: {
    ...theme.typography.body,
    color: palette.text,
    lineHeight: 20,
  },
  encouragementFootnote: {
    ...theme.typography.caption,
    color: palette.textSubtle,
    lineHeight: 18,
  },
  encouragementClose: {
    position: 'absolute',
    top: 12,
    right: 12,
  },

  searchContainer: {
    marginBottom: 18,
  },
  searchInputWrapper: {
    position: 'relative',
  },
  searchInput: {
    height: 56,
    borderRadius: 24,
    paddingLeft: 48,
    paddingRight: 44,
    backgroundColor: '#F5F7FB',
    borderWidth: 0,
    ...theme.typography.body,
    color: palette.text,
  },
  searchIcon: {
    position: 'absolute',
    left: 20,
    top: 20,
  },
  searchClearButton: {
    position: 'absolute',
    right: 16,
    top: 18,
  },
  searchMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  searchMetaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  searchMetaText: {
    ...theme.typography.caption,
    color: palette.textSubtle,
  },
  searchResetButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: '#EEF2F7',
  },
  searchResetText: {
    ...theme.typography.caption,
    color: palette.primary,
    fontWeight: '600',
  },
  filterInputsRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  filterInputWrapper: {
    flex: 1,
    position: 'relative',
  },
  filterInputIcon: {
    position: 'absolute',
    top: 18,
    left: 16,
    zIndex: 1,
  },
  filterInput: {
    height: 48,
    borderRadius: 18,
    paddingLeft: 42,
    paddingRight: 36,
    backgroundColor: '#F5F7FB',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    ...theme.typography.caption,
    color: palette.text,
  },
  filterClearButton: {
    position: 'absolute',
    right: 14,
    top: 14,
  },
  filterTypeaheadContainer: {
    marginTop: 6,
    borderRadius: 16,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.divider,
    overflow: 'hidden',
    maxHeight: 220,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },
  filterTypeaheadEmpty: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    ...theme.typography.caption,
    color: palette.textMuted,
  },
  filterTypeaheadItem: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: palette.divider,
  },
  filterTypeaheadItemLast: {
    borderBottomWidth: 0,
  },
  filterTypeaheadText: {
    ...theme.typography.caption,
    color: palette.text,
  },
  activeFiltersSection: {
    marginBottom: 16,
  },
  activeFiltersHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  activeFiltersTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  activeFiltersTitle: {
    ...theme.typography.caption,
    color: palette.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  activeFiltersClear: {
    ...theme.typography.caption,
    color: palette.primary,
    fontWeight: '600',
  },
  activeFiltersScroll: {
    marginHorizontal: -4,
  },
  activeFiltersRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 4,
  },
  activeFilterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 18,
    backgroundColor: '#EEF2F7',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  activeFilterChipLabel: {
    ...theme.typography.caption,
    color: palette.text,
  },
  activeFilterChipIcon: {
    marginLeft: 2,
  },

  chipsScroll: {
    marginHorizontal: -4,
  },
  chipsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 4,
  },
  chip: {
    paddingHorizontal: 18,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#F5F7FB',
    marginRight: 8,
  },
  chipActive: {
    backgroundColor: palette.text,
  },
  chipLabel: {
    ...theme.typography.caption,
    color: palette.textMuted,
  },
  chipLabelActive: {
    color: '#FFFFFF',
  },

  listScroll: {
    paddingHorizontal: 24,
    paddingTop: 18,
    paddingBottom: 80,
  },
  resultsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  resultsControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  resultsCount: {
    ...theme.typography.caption,
    color: palette.textSubtle,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  resultsMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 18,
  },
  resultsMetaPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 18,
    backgroundColor: palette.surface,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
  },
  resultsMetaPillAccent: {
    backgroundColor: `${palette.primary}12`,
  },
  resultsMetaText: {
    ...theme.typography.caption,
    color: palette.textSubtle,
  },
  resetFiltersButton: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 14,
    backgroundColor: '#F1F5F9',
  },
  resetFiltersLabel: {
    ...theme.typography.caption,
    color: palette.textSubtle,
    fontWeight: '600',
  },
  dateControlsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  dateFilterScroll: {
    flex: 1,
  },
  dateFilterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingRight: 12,
  },
  dateFilterChip: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: '#EEF2F7',
  },
  dateFilterChipActive: {
    backgroundColor: palette.text,
  },
  dateFilterLabel: {
    ...theme.typography.caption,
    color: palette.textMuted,
    fontWeight: '500',
  },
  dateFilterLabelActive: {
    color: '#FFFFFF',
  },
  dateSortButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 18,
    backgroundColor: `${palette.primary}14`,
  },
  dateSortLabel: {
    ...theme.typography.caption,
    color: palette.primary,
    fontWeight: '600',
  },
  listContainer: {
    gap: 18,
    padding: 20,
    borderRadius: 24,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#0F172A',
    shadowOpacity: 0.05,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  listHintRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 16,
    backgroundColor: '#F5F7FB',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  listHintText: {
    ...theme.typography.caption,
    color: palette.textSubtle,
  },
  featuredSection: {
    marginBottom: 26,
    gap: 12,
  },
  featuredLabel: {
    ...theme.typography.caption,
    color: palette.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  featuredCarouselContainer: {
    borderRadius: 26,
    overflow: 'visible',
  },
  featuredCarouselScroll: {
    width: '100%',
  },
  featuredCarouselContent: {
    flexDirection: 'row',
    alignItems: 'stretch',
  },
  featuredCarouselItem: {
    paddingHorizontal: 4,
  },
  featuredCarouselCard: {
    flex: 1,
  },
  featuredCard: {
    borderRadius: 26,
    backgroundColor: palette.primary,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 6,
  },
  featuredImage: {
    width: '100%',
    height: 160,
  },
  featuredContent: {
    paddingHorizontal: 20,
    paddingVertical: 18,
    gap: 12,
  },
  featuredHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  featuredCategoryPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.18)',
  },
  featuredCategoryText: {
    ...theme.typography.caption,
    color: '#FFFFFF',
    fontWeight: '600',
    letterSpacing: 0.6,
  },
  featuredBookmarkButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.18)',
  },
  featuredBookmarkActive: {
    backgroundColor: 'rgba(255,255,255,0.32)',
  },
  featuredTitle: {
    ...theme.typography.subtitle,
    color: '#FFFFFF',
  },
  featuredSummary: {
    ...theme.typography.caption,
    color: 'rgba(255,255,255,0.86)',
    lineHeight: 18,
  },
  featuredFooterRow: {
    marginTop: 6,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  featuredMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  featuredMetaText: {
    ...theme.typography.caption,
    color: 'rgba(255,255,255,0.85)',
  },
  featuredButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
  },
  featuredButtonLabel: {
    ...theme.typography.caption,
    fontWeight: '600',
    color: palette.primary,
  },
  featuredPagination: {
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
  },
  featuredPaginationDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#CBD5F5',
    opacity: 0.6,
  },
  featuredPaginationDotActive: {
    width: 18,
    backgroundColor: palette.primary,
    opacity: 1,
  },

  card: {
    flexDirection: 'row',
    borderRadius: 20,
    backgroundColor: palette.surface,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
    overflow: 'hidden',
    alignItems: 'stretch',
    minHeight: 122,
  },
  cardMedia: {
    width: 108,
    backgroundColor: '#E2E8F0',
    alignSelf: 'stretch',
    overflow: 'hidden',
    flexShrink: 0,
  },
  cardAccentLaw: {
    backgroundColor: '#2563EB',
  },
  cardAccentPersonal: {
    backgroundColor: '#EC4899',
  },
  cardImage: {
    width: '100%',
    height: '100%',
    flex: 1,
  },
  cardMediaFallback: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  cardContent: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 14,
    justifyContent: 'center',
  },
  cardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  cardHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  cardHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  cardCategoryLabel: {
    ...theme.typography.caption,
    fontWeight: '600',
    letterSpacing: 0.8,
    color: palette.textSubtle,
  },
  cardNewBadge: {
    ...theme.typography.caption,
    color: '#FFFFFF',
    backgroundColor: palette.primary,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    overflow: 'hidden',
    letterSpacing: 0.6,
    marginLeft: 8,
  },
  cardTagText: {
    ...theme.typography.caption,
    color: palette.textMuted,
    marginLeft: 8,
    flexShrink: 1,
    textAlign: 'right',
  },
  cardBookmarkButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.surface,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
  },
  cardBookmarkActive: {
    backgroundColor: palette.primary,
  },
  cardSource: {
    ...theme.typography.caption,
    color: palette.textSubtle,
    marginBottom: 4,
  },
  cardTitle: {
    ...theme.typography.body,
    color: palette.text,
    fontWeight: '600',
    marginBottom: 10,
  },
  cardMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  cardMeta: {
    ...theme.typography.caption,
    color: palette.textSubtle,
  },
  dot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: palette.divider,
    marginHorizontal: 8,
  },
  emptyState: {
    marginTop: 40,
    paddingHorizontal: 12,
    alignItems: 'center',
  },
  emptyTitle: {
    ...theme.typography.subtitle,
    color: palette.text,
    marginBottom: 8,
    textAlign: 'center',
  },
  emptySubtitle: {
    ...theme.typography.caption,
    color: palette.textMuted,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 18,
  },
  emptyAction: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 20,
    backgroundColor: palette.primary,
  },
  emptyActionLabel: {
    ...theme.typography.body,
    fontWeight: '600',
    color: '#FFFFFF',
  },
});
