/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Stories
         * @description Retrieves the latest editorial and community stories for the Borderline audience.
         */
        get: operations["listStories"];
        put?: never;
        /**
         * Create Story
         * @description Creates a new Borderline story, uploading any provided images to the media bucket.
         */
        post: operations["createStory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{storyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Story
         * @description Fetches a single Borderline story by its identifier.
         */
        get: operations["getStory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
            version: string;
        };
        BorderlineStory: {
            id: string;
            title: string;
            subtitle: string;
            category: components["schemas"]["StoryCategory"];
            daysAgo: number;
            /** Format: float */
            likes: number;
            countryTag?: string;
            routeTag?: string;
            summary: string;
            keyDetails: string;
            meaning: string;
            /** @default [] */
            images: string[];
            isSpotlight: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        StoryListResponse: {
            data: components["schemas"]["BorderlineStory"][];
        };
        /** @enum {string} */
        StoryCategory: "law" | "personal";
        /**
         * @description Base64-encoded image payload that will be uploaded to the media bucket.
         * @example {
         *       "fileName": "story-lead.png",
         *       "contentType": "image/png",
         *       "data": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR4nGMAAQAABQABDQottAAAAABJRU5ErkJggg=="
         *     }
         */
        StoryImageUpload: {
            /** @description Original file name for the image. Used to derive the stored object key. */
            fileName: string;
            /** @description MIME type for the image (e.g. image/png, image/jpeg). */
            contentType: string;
            /** @description Raw base64-encoded image data. Data URLs are also supported. */
            data: string;
        };
        CreateStoryRequest: {
            title: string;
            subtitle: string;
            category: components["schemas"]["StoryCategory"];
            summary: string;
            keyDetails: string;
            meaning: string;
            countryTag?: string | null;
            routeTag?: string | null;
            /**
             * Format: float
             * @default 0
             */
            likes: number;
            isSpotlight: boolean;
            /**
             * @description Collection of images to upload for the story.
             * @default []
             */
            images: components["schemas"]["StoryImageUpload"][];
        };
        ErrorResponse: {
            error: string;
            details?: string[];
        };
    };
    responses: never;
    parameters: {
        /** @description Unique identifier for the Borderline story. */
        StoryIdPathParam: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listStories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stories retrieved successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryListResponse"];
                };
            };
        };
    };
    createStory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "title": "Spotlight on community support",
                 *       "subtitle": "Editorial desk",
                 *       "category": "law",
                 *       "summary": "Summary content",
                 *       "keyDetails": "Key details",
                 *       "meaning": "Meaningful insights",
                 *       "isSpotlight": true,
                 *       "likes": 12,
                 *       "countryTag": "UK",
                 *       "routeTag": "Skilled Worker",
                 *       "images": [
                 *         {
                 *           "fileName": "story-lead.png",
                 *           "contentType": "image/png",
                 *           "data": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR4nGMAAQAABQABDQottAAAAABJRU5ErkJggg=="
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["CreateStoryRequest"];
            };
        };
        responses: {
            /** @description Story created successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BorderlineStory"];
                };
            };
            /** @description Invalid input supplied. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getStory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier for the Borderline story. */
                storyId: components["parameters"]["StoryIdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Story found. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BorderlineStory"];
                };
            };
            /** @description Story not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
